// packages/snow-ui/button/index.tsx
import React, { ReactNode } from 'react';
import '@snow-design/snow-foundation/button/button.scss'
import { cssClasses } from '@snow-design/snow-foundation/button/constants';
import classNames from "classnames";

const prefixCls = cssClasses.PREFIX;

export type Type = 'default' | 'primary' | 'warning' | 'danger';
export interface ButtonProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type'>{
    children?: ReactNode;
    className?: string;
    style?: React.CSSProperties;
    type?: Type;
    onClick?: React.MouseEventHandler<HTMLButtonElement>;
    onMouseDown?: React.MouseEventHandler<HTMLButtonElement>;
    onMouseEnter?: React.MouseEventHandler<HTMLButtonElement>;
    onMouseLeave?: React.MouseEventHandler<HTMLButtonElement>;
}

const Button: React.FC<ButtonProps> = (props) => {
    const {
        onClick,
        children,
        style,
        className,
        type = 'default',
        ...baseProps
    } = props;

    const classes = classNames(
        className,
        prefixCls,
        {
            [`${prefixCls}-${type}`]: type,
        }
    )

    return (
        <button {...baseProps} style={style} className={classes} onClick={onClick}>
            <span>
                {children}
            </span>
        </button>
    )
}

export default Button;

// packages/vue3/button/index.tsx
import '@snow-design/foundation/button/button.scss'
import { cssClasses } from '@snow-design/foundation/button/constants';
import classNames from "classnames";
import { CssProps, eventType } from '../_utils/type';
import { MouseEventHandler } from '../_utils/eventInterface';
import { withInstall } from "../_utils";
import { defineComponent, PropType } from "vue";

const prefixCls = cssClasses.PREFIX;

export type ThemeType = 'default' | 'primary' | 'warning' | 'danger';

export const buttonProps = () => ({
    type: String as PropType<ThemeType>,
    onClick: eventType<MouseEventHandler>(),
    ...CssProps
});

const Button = defineComponent({
    name: 'SButton',
    compatConfig: { MODE: 3 },
    props: buttonProps(),
    setup(props, { slots }) {
        const {
            style,
            class: className,
            type = 'default',
            ...baseProps
        } = props;

        const classes = classNames(
            className,
            prefixCls,
            {
                [`${prefixCls}-${type}`]: type,
            }
        );

        return () => (
            <button {...baseProps} style={style} class={classes}>
                <span>
                    {slots.default?.()}
                </span>
            </button>
        );
    },
});

export default withInstall(Button);
