// packages/components/config-provider/index.tsx
import React from 'react';
import LocaleProvider from "../_locale";
import { Locale } from "@snow-design/locale/index";

export interface ConfigProviderProps {
  locale?: Locale;
  children: React.ReactNode;
}

const ConfigProvider: React.FC<ConfigProviderProps> = (props) => {
  const {
    locale,
    children,
  } = props;

  let childNode = (
    <>
      {children}
    </>
  );

  if (locale) {
    childNode = (
      <LocaleProvider locale={locale}>
        {childNode}
      </LocaleProvider>
    )
  }

  return childNode
}

export default ConfigProvider;

// packages/vue3/config-provider/index.tsx
import LocaleProvider from "../_locale";
import { Locale } from "@snow-design/locale/index";
import { defineComponent, PropType } from "vue";
import { withInstall } from "../_utils/type";

export interface ConfigProviderProps {
  locale?: Locale;
}

const ConfigProvider = defineComponent({
  name: 'SConfigProvider',
  props: {
    locale: {
      type: Object as PropType<Locale>,
    }
  },
  setup(props, {slots}) {
    const {
      locale,
    } = props;
    const children = slots.default?.();
    let childNode = (
      <>
        {children}
      </>
    );

    if (locale) {
      childNode = (
        <LocaleProvider locale={locale}>
          {childNode}
        </LocaleProvider>
      )
    }
    return () => childNode
  }
})


export default withInstall(ConfigProvider);
