// packages/vue3/_locale/useLocale.tsx
import { inject, computed } from 'vue';
import type { Locale, LocaleComponentName } from '@snow-design/locale';
import { en_US as defaultLocaleData } from '@snow-design/locale';
import { VueSnowLocale } from './index';

const useLocale = <C extends LocaleComponentName = LocaleComponentName>(
    componentName: C,
    defaultLocale?: Locale[C] | (() => Locale[C]),
): readonly [NonNullable<Locale[C]>, string] => {
    const localeData = inject<VueSnowLocale>('localeData', {} as VueSnowLocale);

    const getLocale = computed(() => {
        const locale = defaultLocale || defaultLocaleData[componentName];
        const localeFromContext = localeData.snowLocale?.[componentName] ?? {};
        return {
            ...(typeof locale === 'function' ? locale() : locale),
            ...(localeFromContext || {}),
        };
    });

    const getLocaleCode = computed(() => {
        const localeCode = localeData.snowLocale?.locale;
        return localeCode || defaultLocaleData.locale;
    });

    return [getLocale.value, getLocaleCode.value];
};

export default useLocale;

// packages/components/_locale/useLocale.tsx
import * as React from 'react';
import LocaleContext from './context';
import type { Locale, LocaleComponentName } from '@snow-design/locale/index';
import defaultLocaleData from '@snow-design/locale/en_US';

const useLocale = <C extends LocaleComponentName = LocaleComponentName>(
  componentName: C,
  defaultLocale?: Locale[C] | (() => Locale[C]),
): readonly [NonNullable<Locale[C]>, string] => {
  const fullLocale = React.useContext<Locale | undefined>(LocaleContext);

  // 返回值为 Locale 对象
  const getLocale = React.useMemo<NonNullable<Locale[C]>>(() => {
    const locale = defaultLocale || defaultLocaleData[componentName]; // 默认兜底
    const localeFromContext = fullLocale?.[componentName] ?? {}; // 从 Context 获取
    return {
      ...(typeof locale === 'function' ? locale() : locale),
      ...(localeFromContext || {}),
    };
  }, [componentName, defaultLocale, fullLocale]);

  // 返回值为 Locale Code zh_CN en_US 等
  const getLocaleCode = React.useMemo<string>(() => {
    const localeCode = fullLocale?.locale;
    return localeCode || defaultLocaleData.locale;;
  }, [fullLocale]);

  return [getLocale, getLocaleCode] as const;
};

export default useLocale;
